<a href="https://colab.research.google.com/github/Mina0402/EU_M_Math-Repository/blob/main/Chap08_Ex_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.random as random
import scipy as sp
from pandas import Series, DataFrame
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

import sklearn

%precision 3

'%.3f'

In [ ]:
#重回帰
import requests, zipfile
import io

url='https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
res=requests.get(url).content

auto=pd.read_csv(io.StringIO(res.decode('utf-8')), header=None)

auto.columns=['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration','num-of-doors',
             'body-style','drive-wheels','engine-location','wheel-base','length','width','height',
             'curb-weight','engine-type','num-of-cylinders','engine-size','fuel-system','bore',
             'stroke','compression-ration','horsepower','peak-rpm','city-mpg','highway-mpg','price']

In [ ]:
print('自動車データの形式:',format(auto.shape))

自動車データの形式: (205, 26)


In [ ]:
auto.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ration horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68                9.0        111      5000       21   
1         mpfi  3.47    2.68                9.0        111      5000       21   
2         mpfi  2.68    3.47                9.0        154      5000       19   
3         mpfi  3.19    3.40               10.0        102      5500       24   
4         mpfi  3.19    3.40                8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [ ]:
#データ整理
auto=auto[['price', 'horsepower', 'width', 'height']]
auto.isin(['?']).sum()

price         4
horsepower    2
width         0
height        0
dtype: int64

In [ ]:
auto=auto.replace('?', np.nan).dropna()
print('自動車データ形式:',format(auto.shape))

自動車データ形式: (199, 4)


In [ ]:
#型の変換
print('データ型の確認(型変換前)\n', format(auto.dtypes))


データ型の確認(型変換前)
 price          object
horsepower     object
width         float64
height        float64
dtype: object


In [ ]:
auto=auto.assign(price=pd.to_numeric(auto.price))
auto=auto.assign(horsepower=pd.to_numeric(auto.horsepower))
print('データ型の確認(型変換後)\n', format(auto.dtypes))

データ型の確認(型変換後)
 price           int64
horsepower      int64
width         float64
height        float64
dtype: object


In [ ]:
#相関の確認
auto.corr()

price  horsepower     width    height
price       1.000000    0.810533  0.753871  0.134990
horsepower  0.810533    1.000000  0.615315 -0.087407
width       0.753871    0.615315  1.000000  0.309223
height      0.134990   -0.087407  0.309223  1.000000

In [ ]:
#モデル構築と評価
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X=auto.drop('price', axis=1)
y=auto['price']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=0)

#重回帰クラスの初期化と学習
model=LinearRegression()
model.fit(X_train,y_train)

#決定係数の表示
print('決定係数(train):{:.3f}'.format(model.score(X_train,y_train)))
print('決定係数(test):{:.3f}'.format(model.score(X_test,y_test)))

#回帰係数と切片の表示
print('\n回帰係数\n():',format(pd.Series(model.coef_, index=X.columns)))
print('切片:{:.3f}',format(model.intercept_))

決定係数(train):0.733
決定係数(test):0.737

回帰係数
(): horsepower      81.651078
width         1829.174506
height         229.510077
dtype: float64
切片:{:.3f} -128409.0463033857


In [ ]:
#練習問題8-1
auto1=pd.read_csv(io.StringIO(res.decode('utf-8')), header=None)

auto1.columns=['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration','num-of-doors',
             'body-style','drive-wheels','engine-location','wheel-base','length','width','height',
             'curb-weight','engine-type','num-of-cylinders','engine-size','fuel-system','bore',
             'stroke','compression-ration','horsepower','peak-rpm','city-mpg','highway-mpg','price']
print('自動車データの形式:',format(auto1.shape))

自動車データの形式: (205, 26)


In [ ]:
auto1.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ration horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68                9.0        111      5000       21   
1         mpfi  3.47    2.68                9.0        111      5000       21   
2         mpfi  2.68    3.47                9.0        154      5000       19   
3         mpfi  3.19    3.40               10.0        102      5500       24   
4         mpfi  3.19    3.40                8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [ ]:
auto1=auto1[['price',  'width', 'engine-size']]
auto1.isin(['?']).sum()

price          4
width          0
engine-size    0
dtype: int64

In [ ]:
auto1=auto1.replace('?', np.nan).dropna()

In [ ]:
print('データ型の確認(型変換前)\n', format(auto1.dtypes))

データ型の確認(型変換前)
 price           object
width          float64
engine-size      int64
dtype: object


In [ ]:
auto1=auto1.assign(price=pd.to_numeric(auto1.price))
print('データ型の確認(型変換後)\n', format(auto1.dtypes))

データ型の確認(型変換後)
 price            int64
width          float64
engine-size      int64
dtype: object


In [ ]:
X1 = auto1[['width', 'engine-size']]
y1 = auto1['price']

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.5, random_state=0)

model = LinearRegression()
model.fit(X1_train, y1_train)

print('決定係数(train): {:.3f}'.format(model.score(X1_train, y1_train)))
print('決定係数(test): {:.3f}'.format(model.score(X1_test, y1_test)))

print('\n回帰係数:')
print(pd.Series(model.coef_, index=X1.columns))
print('切片: {:.3f}'.format(model.intercept_))

決定係数(train): 0.783
決定係数(test): 0.778

回帰係数:
width          1261.735518
engine-size     109.526787
dtype: float64
切片: -84060.643


In [ ]:
#ロジスティクス回帰
url2='https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
res2=requests.get(url2).content

adult=pd.read_csv(io.StringIO(res2.decode('utf-8')), header=None)

adult.columns=['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
               'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',
               'native-country', 'flg-50K']

print('データの形式:()'.format(adult.shape))
print('欠損の数:()',format(adult.isnull().sum().sum()))

adult.head()

データの形式:()
欠損の数:() 0


age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country flg-50K  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [ ]:
adult.groupby('flg-50K').size()

flg-50K
 <=50K    24720
 >50K      7841
dtype: int64

In [ ]:
#「fin_flg」カラムを追加し、「flg-50K」カラムが「>50K」なら1、そうでなければ0で
adult['fin_flg']=adult['flg-50K'].map(lambda x: 1 if x==' >50K' else 0)
adult.groupby('fin_flg').size()

fin_flg
0    24720
1     7841
dtype: int64

In [ ]:
#モデル構築と評価
from sklearn.linear_model import LogisticRegression

X2=adult[['age','fnlwgt','education-num','capital-gain','capital-loss']]
y2=adult['fin_flg']

X2_train, X2_test, y2_train, y2_test=train_test_split(X2, y2, test_size=0.5, random_state=0)

model2=LogisticRegression()
model2.fit(X2_train,y2_train)

print('正解率(train):{:.3f}'.format(model2.score(X2_train, y2_train)))
print('正解率(test):{:.3f}'.format(model2.score(X2_test,y2_test)))

正解率(train):0.797
正解率(test):0.798


In [ ]:
model2.coef_

array([[-1.185e-02, -4.379e-06, -2.774e-03,  3.274e-04,  7.532e-04]])

In [ ]:
np.exp(model2.coef_)

array([[0.988, 1.   , 0.997, 1.   , 1.001]])

In [ ]:
#予測精度を上げるスケーリング
from sklearn.preprocessing import StandardScaler

#標準化処理
sc=StandardScaler()
sc.fit(X2_train)
X2_train_std=sc.transform(X2_train)
X2_test_std=sc.transform(X2_test)

model2=LogisticRegression()
model2.fit(X2_train_std,y2_train)

print('正解率(train):{:.3f}'.format(model2.score(X2_train_std, y2_train)))
print('正解率(test):{:.3f}'.format(model2.score(X2_test_std,y2_test)))

正解率(train):0.811
正解率(test):0.810


In [ ]:
#練習問題8-2
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

X3 = pd.DataFrame(cancer.data, columns=cancer.feature_names)

y3 = pd.Series(cancer.target, name='target')

print(X.head())
print(y.head())



   horsepower  width  height
0         111   64.1    48.8
1         111   64.1    48.8
2         154   65.5    52.4
3         102   66.2    54.3
4         115   66.4    54.3
0    13495
1    16500
2    16500
3    13950
4    17450
Name: price, dtype: int64


In [ ]:
X3_train, X3_test, y3_train, y3_test=train_test_split(X3, y3, test_size=0.3, random_state=0)

model3=LogisticRegression()
model3.fit(X3_train, y3_train)

print('訓練データに対する精度:{:.3f}'.format(model2.score(X2_train, y2_train)))
print('テストデータに対する精度:{:.3f}'.format(model2.score(X2_test,y2_test)))

訓練データに対する精度:0.239
テストデータに対する精度:0.243


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [ ]:
#練習問題8-3
model3.coef_


array([[ 1.152,  0.378,  0.211, -0.01 , -0.047, -0.205, -0.291, -0.124,
        -0.09 , -0.012,  0.061,  0.474,  0.249, -0.117, -0.003, -0.037,
        -0.06 , -0.016, -0.016, -0.003,  1.277, -0.439, -0.273, -0.017,
        -0.084, -0.645, -0.856, -0.25 , -0.232, -0.065]])

In [ ]:
np.exp(model3.coef_)

array([[3.165, 1.459, 1.234, 0.99 , 0.954, 0.815, 0.747, 0.883, 0.914,
        0.988, 1.063, 1.607, 1.283, 0.89 , 0.997, 0.964, 0.942, 0.984,
        0.984, 0.997, 3.587, 0.645, 0.761, 0.983, 0.92 , 0.525, 0.425,
        0.779, 0.793, 0.937]])

In [ ]:
sc=StandardScaler()
sc.fit(X3_train)
X3_train_std=sc.transform(X3_train)
X3_test_std=sc.transform(X3_test)

model3.fit(X3_train_std,y3_train)

print('訓練データに対する精度:{:.3f}'.format(model3.score(X3_train_std, y3_train)))
print('テストデータに対する精度:{:.3f}'.format(model3.score(X3_test_std,y3_test)))


訓練データに対する精度:0.990
テストデータに対する精度:0.977
